jobs:
- job: copr_build
  metadata:
    targets:
    - centos-stream-x86_64
  trigger: pull_request
- job: copr_build
  trigger: commit
  actions:
    # bump spec so we get release starting with 2 and hence all master builds will
    # have higher NVR than all the PR builds
    post-upstream-clone:
    - rpmdev-bumpspec --comment='latest upstream build' ./packaging/epel/convert2rhel.spec
  metadata:
    branch: master
    owner: "ttomecek"
    project: rpm-python-38
    targets:
    - centos-stream-x86_64
specfile_path: SPECS/rpm.spec
upstream_ref: sg-start
