jobs:
- job: copr_build
  metadata:
    targets:
    - centos-stream-x86_64
  trigger: pull_request
- job: copr_build
  trigger: commit
  metadata:
    branch: master
    owner: ttomecek
    project: rpm-python-38
    targets:
    - centos-stream-x86_64
specfile_path: SPECS/rpm.spec
upstream_ref: sg-start
